// Script body executed inside the embedder iframe. Loads transformers.js
// at runtime from the jsDelivr CDN as a true ES module — this sidesteps
// the Electron renderer's hybrid (node+browser) environment, where the
// bundled transformers.js picks the node backend and fails.
//
// The script has no local dependencies. It is injected verbatim into the
// iframe's srcdoc as <script type="module">. Kept as a plain concatenated
// string (no inner template-literal interpolation) so the outer template
// literal in semantic.ts stays readable and esbuild does nothing clever
// with the contents.

const LINES: string[] = [
	'const TRANSFORMERS_URL = "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.0";',
	'',
	'// Device fallback ladder. WebGPU tiers were in here (mirroring Smart',
	'// Connections) but bge-micro-v2 hits a JSEP kernel failure at',
	'// /embeddings/Add_1 on every WebGPU backend in this Chromium build —',
	'// the pipeline loads fine, a short warmup passes, then real input',
	'// trips int64 index handling. WASM q8 embeds a paragraph in ~20ms,',
	'// which is fast enough for a one-shot reindex. If you switch to a',
	'// model with working WebGPU kernels (e.g. Snowflake/snowflake-arctic-',
	'// embed-xs), reintroduce the webgpu_* entries ahead of the WASM ones.',
	'const DEVICE_CONFIGS = [',
	'	["wasm_q8",     { dtype: "q8" }],',
	'	["wasm_q4",     { dtype: "q4" }],',
	'	["wasm_auto",   {} ],',
	'];',
	'',
	'let pipe = null;',
	'let tokenizer = null;',
	'let active_config_key = null;',
	'',
	'async function is_webgpu_available() {',
	'	if (!("gpu" in navigator)) return false;',
	'	try {',
	'		const adapter = await navigator.gpu.requestAdapter();',
	'		return !!adapter;',
	'	} catch (_err) {',
	'		return false;',
	'	}',
	'}',
	'',
	'async function load_pipeline(model_key) {',
	'	const mod = await import(TRANSFORMERS_URL);',
	'	const pipeline = mod.pipeline;',
	'	const env = mod.env;',
	'	const AutoTokenizer = mod.AutoTokenizer;',
	'	env.allowLocalModels = false;',
	'	if (typeof env.useBrowserCache !== "undefined") env.useBrowserCache = true;',
	'',
	'	const has_gpu = await is_webgpu_available();',
	'	let last_error = null;',
	'	for (const entry of DEVICE_CONFIGS) {',
	'		const config_key = entry[0];',
	'		const config = entry[1];',
	'		if (config.device === "webgpu" && !has_gpu) continue;',
	'		let candidate = null;',
	'		try {',
	'			console.log("[vault-mcp iframe] trying " + config_key);',
	'			candidate = await pipeline("feature-extraction", model_key, config);',
	'			// Warmup: some configs (notably bge-micro-v2 on WebGPU) load',
	'			// cleanly but fail at first inference with a kernel error —',
	'			// and single short strings do not always trip the bug. Run a',
	'			// batch of two longer, vocabulary-varied inputs so we exercise',
	'			// the same code path that real reindex traffic will.',
	'			await candidate([',
	'				"The quick brown fox jumps over the lazy dog beside the riverbank in autumn.",',
	'				"Embeddings transform text into dense vector representations for similarity search."',
	'			], { pooling: "mean", normalize: true });',
	'			pipe = candidate;',
	'			active_config_key = config_key;',
	'			console.log("[vault-mcp iframe] loaded on " + config_key);',
	'			break;',
	'		} catch (err) {',
	'			console.warn("[vault-mcp iframe] " + config_key + " failed", err);',
	'			last_error = err;',
	'			try {',
	'				if (candidate && typeof candidate.destroy === "function") candidate.destroy();',
	'				else if (candidate && typeof candidate.dispose === "function") candidate.dispose();',
	'			} catch (_dispose_err) { /* best effort */ }',
	'			candidate = null;',
	'		}',
	'	}',
	'	if (!pipe) throw last_error || new Error("All device configs failed");',
	'',
	'	try {',
	'		tokenizer = await AutoTokenizer.from_pretrained(model_key);',
	'	} catch (err) {',
	'		// Tokenizer is nice-to-have (used for count_tokens). Embedding works',
	'		// without it; count_tokens will fall back to a char-based estimate.',
	'		console.warn("[vault-mcp iframe] tokenizer load failed", err);',
	'		tokenizer = null;',
	'	}',
	'}',
	'',
	'// Truncate a text so the tokenizer will produce at most max_tokens ids.',
	'// Passing truncation options through pipe(...) does not reliably clip',
	'// in transformers.js 3.x — ORT then throws a raw pointer ("44383360")',
	'// when the sequence exceeds max_position_embeddings (512). So we do the',
	'// truncation ourselves: measure tokens, slice text proportionally, and',
	'// repeat until we fit. Vault content includes CJK (textbook analysis),',
	'// which at ~1 token/char blows past 512 inside a 1500-char chunk.',
	'async function prepare_input(text, max_tokens) {',
	'	if (!tokenizer) {',
	'		// Char-level fallback: assume worst-case 1 token/char.',
	'		return text.length > max_tokens ? text.slice(0, max_tokens) : text;',
	'	}',
	'	let current = text;',
	'	let count = (await tokenizer(current)).input_ids.data.length;',
	'	let iterations = 0;',
	'	while (count > max_tokens && current.length > 40 && iterations < 8) {',
	'		const ratio = max_tokens / count;',
	'		let target = Math.max(40, Math.floor(current.length * ratio * 0.85));',
	'		current = current.slice(0, target);',
	'		const last_space = current.lastIndexOf(" ");',
	'		if (last_space > 40) current = current.slice(0, last_space);',
	'		count = (await tokenizer(current)).input_ids.data.length;',
	'		iterations++;',
	'	}',
	'	if (count > max_tokens) {',
	'		// Hard char cap if the proportional loop did not converge.',
	'		current = current.slice(0, Math.max(40, Math.floor(current.length * max_tokens / count * 0.8)));',
	'	}',
	'	return current;',
	'}',
	'',
	'async function embed_batch(texts) {',
	'	if (!pipe) throw new Error("Pipeline not loaded");',
	'	if (!Array.isArray(texts) || texts.length === 0) return [];',
	'	// max_position_embeddings is 512 for bge-micro-v2. Reserve 2 for',
	'	// [CLS] and [SEP] that the tokenizer adds automatically.',
	'	const MAX_TOKENS = 510;',
	'	// Embed one input at a time. Smart Connections\\u0027s bge-micro-v2',
	'	// config uses batch_size: 1, and sending >1 text to this ORT/WASM q8',
	'	// build reproduces the raw-pointer crash ("44323000"-style) even',
	'	// after pre-truncation. Per-item also lets us skip a bad chunk',
	'	// without killing the whole file\\u0027s embedding run.',
	'	const out = [];',
	'	let dim = 0;',
	'	for (const text of texts) {',
	'		const prepared = await prepare_input(text, MAX_TOKENS);',
	'		try {',
	'			const resp = await pipe(prepared, { pooling: "mean", normalize: true });',
	'			dim = resp.dims[resp.dims.length - 1];',
	'			out.push(Array.from(resp.data));',
	'		} catch (err) {',
	'			console.error("[vault-mcp iframe] single-item embed failed, zero-filling", err);',
	'			if (!dim) dim = 384; // best-effort default for this model',
	'			out.push(new Array(dim).fill(0));',
	'		}',
	'	}',
	'	return { vectors: out, dim: dim };',
	'}',
	'',
	'async function count_tokens(input) {',
	'	if (!tokenizer) return { tokens: Math.ceil(String(input || "").length / 4) };',
	'	const result = await tokenizer(input);',
	'	return { tokens: result.input_ids.data.length };',
	'}',
	'',
	'async function unload() {',
	'	try {',
	'		if (pipe && typeof pipe.destroy === "function") pipe.destroy();',
	'		else if (pipe && typeof pipe.dispose === "function") pipe.dispose();',
	'	} catch (err) {',
	'		console.warn("[vault-mcp iframe] unload error", err);',
	'	}',
	'	pipe = null;',
	'	tokenizer = null;',
	'	active_config_key = null;',
	'	return { unloaded: true };',
	'}',
	'',
	'async function process_message(data) {',
	'	const method = data.method;',
	'	const params = data.params || {};',
	'	const id = data.id;',
	'	try {',
	'		let result;',
	'		switch (method) {',
	'			case "load":',
	'				await load_pipeline(params.model_key);',
	'				result = { loaded: true, active_config_key: active_config_key };',
	'				break;',
	'			case "embed_batch":',
	'				result = await embed_batch(params.texts);',
	'				break;',
	'			case "count_tokens":',
	'				result = await count_tokens(params.input);',
	'				break;',
	'			case "unload":',
	'				result = await unload();',
	'				break;',
	'			default:',
	'				throw new Error("Unknown method: " + method);',
	'		}',
	'		return { id: id, result: result };',
	'	} catch (err) {',
	'		const msg = (err && err.message) ? err.message : String(err);',
	'		console.error("[vault-mcp iframe] " + method + " failed", err);',
	'		return { id: id, error: msg };',
	'	}',
	'}',
	'',
	'window.addEventListener("message", async (event) => {',
	'	const data = event.data;',
	'	if (!data || typeof data !== "object") return;',
	'	if (data.iframe_id !== IFRAME_ID_SENTINEL) return;',
	'	if (typeof data.id !== "string") return;',
	'	const response = await process_message(data);',
	'	response.iframe_id = IFRAME_ID_SENTINEL;',
	'	window.parent.postMessage(response, "*");',
	'});',
	'',
	'// Boot signal. Parent waits for this before sending "load" so we avoid a',
	'// race between iframe.onload (fires before deferred modules run in some',
	'// versions) and the message listener registration above.',
	'window.parent.postMessage({ iframe_id: IFRAME_ID_SENTINEL, id: "__ready__", result: { ready: true } }, "*");',
];

// Build the script template; parent substitutes IFRAME_ID_SENTINEL at inject time.
export function buildEmbedderIframeScript(iframeId: string): string {
	const body = LINES.join("\n");
	// Hard-code the iframe id so messages from other iframes sharing the
	// parent window (e.g. Smart Connections) are ignored.
	const idLiteral = JSON.stringify(iframeId);
	return `const IFRAME_ID_SENTINEL = ${idLiteral};\n${body}`;
}
